resource_group_name = "geocall-dev-rg"
location            = "centralus"
vm_name             = "geocall-dev-vm"
admin_username      = "geocalladmin"
admin_password      = "V@lk7r1eValhalla"
vm_size             = "Standard_B1s"
